FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETARCH
COPY linux/${TARGETARCH}/remote-write-inspector /usr/local/bin/remote-write-inspector
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/remote-write-inspector"]
